# See lib/config/main_config.py for more details.
GENERAL:
  DESCRIPTION: "Training ProMFT-Deep on DepthTrack dataset (backbone: OSTrack-384)."
  TITLE: ProMFT-Deep on DepthTrack (384)
DATA:
  MAX_SAMPLE_INTERVAL: 200
  MEAN:
  - 0.485
  - 0.456
  - 0.406
  SEARCH:
    CENTER_JITTER: 3
    FACTOR: 4.0
    SCALE_JITTER: 0.25
    SIZE: 384
    NUMBER: 1
  STD:
  - 0.229
  - 0.224
  - 0.225
  TEMPLATE:
    CENTER_JITTER: 0
    FACTOR: 2.0
    SCALE_JITTER: 0
    SIZE: 192
  TRAIN:
    DATASETS:
    - NAME: DepthTrack_train
      # PATH: datasets/depthtrack/train
      PATH: datasets/depthtrack
      RATIO: 1
    SAMPLE_PER_EPOCH: 60000
  # VAL:
  #   DATASETS:
  #   - NAME: DepthTrack_val
  #     PATH: datasets/depthtrack/train
  #     RATIO: 1
  #   SAMPLE_PER_EPOCH: 10000
  TEST:
    DATASETS:
    - NAME: DepthTrack_test
      # PATH: datasets/depthtrack/test
      PATH: datasets/depthtrack
      RATIO: 1
MODEL:
  PRETRAIN_FILE: "./pretrained/ostrack/vitb_384_mae_ce_32x4_ep300/OSTrack_ep0300.pth.tar"
  EXTRA_MERGER: False
  RETURN_INTER: False
  BACKBONE:
    TYPE: vit_base_patch16_224_ce_prompt
    STRIDE: 16
    CE_LOC: [3, 6, 9]
    CE_KEEP_RATIO: [0.7, 0.7, 0.7]
    CE_TEMPLATE_RANGE: 'CTR_POINT'  # choose between ALL, CTR_POINT, CTR_REC, GT_BOX
  HEAD:
    TYPE: CENTER
    NUM_CHANNELS: 256
TRAIN:
  BACKBONE_MULTIPLIER: 0.1
  DROP_PATH_RATE: 0.1
  CE_START_EPOCH: 4  # candidate elimination start epoch 1/15
  CE_WARM_EPOCH: 16  # candidate elimination warm up epoch 4/15
  # BATCH_SIZE: 16
  BATCH_SIZE: 8
  EPOCH: 60
  GIOU_WEIGHT: 2.0
  L1_WEIGHT: 5.0
  GRAD_CLIP_NORM: 0.1
  LR: 0.0004
  LR_DROP_EPOCH: 48  # 4/5
  NUM_WORKER: 10
  OPTIMIZER: ADAMW
  PRINT_INTERVAL: 50
  SCHEDULER:
    TYPE: step
    DECAY_RATE: 0.1
  VAL_EPOCH_INTERVAL: 5
  WEIGHT_DECAY: 0.0001
  AMP: False
  PROMPT:
    TYPE: promft_deep
  FIX_BN: true
  SAVE_EPOCH_INTERVAL: 1
  SAVE_LAST_N_EPOCH: 1
TEST:
  EPOCH: 60
  SEARCH_FACTOR: 4.0
  SEARCH_SIZE: 384
  TEMPLATE_FACTOR: 2.0
  TEMPLATE_SIZE: 192
